Add TensorFlow Serving Cluster Scripts for the tutorial PR below:
oscarlab/graphene-contrib pull request #1
Opened 2021-03-03 05:48 UTC by RodgerZhu

Add the scripts for the TensorFlow Serving Cluster
tutorial. 
It includes two parts: Kubernetes and TensorFlow Serving.
The tutorial PR below:
https://github.com/oscarlab/graphene/pull/2194

2021-03-03 13:00 UTC, dimakuv requested changes
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 15 unresolved discussions (waiting on @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs61Ek6KK76mJDpNFv:-MUs61Ek6KK76mJDpNFw:bre0pf4) (no related file):*
We will fix the commit message during the final rebase.

But I'm not sure how to link to the tutorial PR (is it even needed? Probably not.)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs9jJI5wxfy6JGR97D:-MUs9jJI5wxfy6JGR97E:bvou1b8) (no related file):*
There is no `tensorflow-serving-cluster/README.md` file. Can you add it? Please copy-paste some introduction text in this file from the tutorial.

Also, please explain the sub-directory and sub-files structure of this project in the README file.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs9yac5SjN1Inv44FA:-MUs9yac5SjN1Inv44FB:b-pkhuac) (no related file):*
There is no copyright information on some of the files. Please add the corresponding copyright to your files (whatever license you choose + company + year at least).

---
___
*[tensorflow-serving-cluster/kubernetes/install_kubernetes.sh, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs9cJh7noF1ypqnU7d:-MUs9cJi8oR4idlqbYQC:b-t2qxiy) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/kubernetes/install_kubernetes.sh#L1)):*
> ```Shell
> # Setup kubernetes environments
> ```

Don't you want to add to this file:
```
#!/bin/bash
set -e
```
___
*[tensorflow-serving-cluster/kubernetes/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs7kVV4hMYGBHQqHQQ:-MUs7kVV4hMYGBHQqHQR:bbm9jn3) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/kubernetes/README.md#L1)):*
> ```Markdown
> 1. Update system time and install kubernetes
> ```

Could you add some introduction to this file? You can copy-paste a couple sentences from the tutorial.

Right now, it's completely unclear what this Kubernetes stuff achieves.
___
*[tensorflow-serving-cluster/kubernetes/README.md, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs6g-U7dExsi3ouJGN:-MUs6g-U7dExsi3ouJGO:b-nkvyjt) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/kubernetes/README.md#L27)):*
> ```Markdown
> 
> 4. Setup ingress-nginx service
> > ingress-ngnix/readme.txt
> ```

Wrong name, should be `ingress-nginx`
___
*[tensorflow-serving-cluster/kubernetes/flannel/readme.txt, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs7sF36KS0u_BuSo8a:-MUs7sF36KS0u_BuSo8b:b-kin8sh) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/kubernetes/flannel/readme.txt#L1)):*
> ```vimhelp
> # Deploy service
> ```

Why do you use `.txt` file for this? Why not `.md`?

If there is no particular reason for keeping this, then please change all TXT files to the MD format.
___
*[tensorflow-serving-cluster/kubernetes/ingress-nginx/readme.txt, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs83ElBl-ScsQcEHuy:-MUs83ElBl-ScsQcEHuz:b-sr5dr4) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/kubernetes/ingress-nginx/readme.txt#L1)):*
> ```vimhelp
> # https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/baremetal/deploy.yaml
> ```

Ditto (change TXT to MD)
___
*[tensorflow-serving-cluster/kubernetes/ingress-nginx/readme.txt, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs73zj9iuR6Y2C0ZoX:-MUs73zj9iuR6Y2C0ZoY:b8x49ft) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/kubernetes/ingress-nginx/readme.txt#L12)):*
> ```vimhelp
> # Check status
> kubectl get -n ingress-nginx service/ingress-nginx-controller -o yaml
> kubectl get -n ingress-nginx deployment.apps/ingress-nginx-controller -o yaml
> ```

Please add a newline.
___
*[tensorflow-serving-cluster/tensorflow-serving/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs7Voe1ZK4cGi35Zmn:-MUs7Voe1ZK4cGi35Zmo:b6vbvrr) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/tensorflow-serving/README.md#L1)):*
> ```Markdown
> ## Server
> ```

Could you add some introduction to this file? You can copy-paste a couple sentences from the tutorial.

Right now, it's completely unclear what this whole thing is for.
___
*[tensorflow-serving-cluster/tensorflow-serving/client/utils.py, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs8MC48t2lVYuDjLgR:-MUs8MC48t2lVYuDjLgS:b-i1jhmj) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/tensorflow-serving/client/utils.py#L29)):*
> ```Python
>     nparr = np.fromstring(imgString, np.uint8)
>     image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
>     return image
> ```

Please add a newline
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile, line 53 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs8Vo7Bk6ATGzfttj_:-MUs8Vo85WJJfaIausWb:bscg2om) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile#L53)):*
> ```Dockerfile
> RUN git clone https://github.com/oscarlab/graphene.git ${GRAPHENEDIR} \
>     && cd ${GRAPHENEDIR} \
>     && git checkout 303528131c67f58aeee677397ade9593f222ae88
> ```

Can you put this `3035...` constant in an `ENV` variable? This will make it clear that you're using a specific Graphene commit.
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/tensorflow_model_server.manifest.attestation.template, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs8sE300KmU2yY60Vf:-MUs8sE300KmU2yY60Vg:b-tiouhe) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/tensorflow-serving/docker/tensorflow_model_server.manifest.attestation.template#L74)):*
> ```
> # the application can create is (sgx.thread_num - 2).
> #
> # We (somewhat arbitrarily) specify 16 threads since TF-Serving is multithreaded.
> ```

`16` -> `1024`
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/tensorflow_model_server.manifest.nonattestation.template, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs9---Be30OM6fdAha:-MUs9---Be30OM6fdAhb:b-tiouhe) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/tensorflow-serving/docker/tensorflow_model_server.manifest.nonattestation.template#L58)):*
> ```
> # the application can create is (sgx.thread_num - 2).
> #
> # We (somewhat arbitrarily) specify 16 threads since TF-Serving is multithreaded.
> ```

`16` -> `1024`
___
*[tensorflow-serving-cluster/tensorflow-serving/kubernetes/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MUs992O52eDzYO0S7Gj:-MUs992O52eDzYO0S7Gk:bj2cres) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/0ca9135322ce3be48b49120200d739e45f48bb44/tensorflow-serving-cluster/tensorflow-serving/kubernetes/README.md#L1)):*
> ```Markdown
> ## Server 
> ```

Could you add some introduction to this file? You can copy-paste a couple sentences from the tutorial.

And why do you have two READMEs for Kubernetes? Wha [...]

2021-03-05 09:12 UTC, dimakuv requested changes
> Reviewed 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 37 unresolved discussions (waiting on @mkow and @RodgerZhu)

___
*[tensorflow-serving-cluster/README.md, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0aHr15IgjoYzgh2CG:-MV0aHr26Feuw4v1-4Vf:b-w0ov3m) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L3)):*
> ```Markdown
> # TensorFlow Serving Cluster PPML Tutorial Scripts
> 
> This directory contains the scrips package for [TensorFlow Serving cluster PPML tutorial](https://graphene.readthedocs.io/en/latest/tutorials/tensorflow-serving-cluster/index.html), including two packages:
> ```

`scrips` -> `scripts`
___
*[tensorflow-serving-cluster/README.md, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0aRAp3j_baIp9dbHQ:-MV0aRAp3j_baIp9dbHR:b-f2yg42) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L3)):*
> ```Markdown
> # TensorFlow Serving Cluster PPML Tutorial Scripts
> 
> This directory contains the scrips package for [TensorFlow Serving cluster PPML tutorial](https://graphene.readthedocs.io/en/latest/tutorials/tensorflow-serving-cluster/index.html), including two packages:
> ```

`including two packages`- > `split into two sub-directories`
___
*[tensorflow-serving-cluster/README.md, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0aO7P-2aAsHI0mjuN:-MV0aO7P-2aAsHI0mjuO:b2tnk5r) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L4)):*
> ```Markdown
> 
> This directory contains the scrips package for [TensorFlow Serving cluster PPML tutorial](https://graphene.readthedocs.io/en/latest/tutorials/tensorflow-serving-cluster/index.html), including two packages:
> - Kebubernetes. This directory contains Yaml configuration files of the serices
> ```

Typo: `Kebubernetes` -> `Kubernetes`
___
*[tensorflow-serving-cluster/README.md, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0ac4A6sC0pCS1Fe1u:-MV0ac4A6sC0pCS1Fe1v:b-balb3w) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L4)):*
> ```Markdown
> 
> This directory contains the scrips package for [TensorFlow Serving cluster PPML tutorial](https://graphene.readthedocs.io/en/latest/tutorials/tensorflow-serving-cluster/index.html), including two packages:
> - Kebubernetes. This directory contains Yaml configuration files of the serices
> ```

`serices` -> `services`
___
*[tensorflow-serving-cluster/README.md, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0aegM9WSScv035qbR:-MV0aegM9WSScv035qbS:b9dbudz) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L5)):*
> ```Markdown
> This directory contains the scrips package for [TensorFlow Serving cluster PPML tutorial](https://graphene.readthedocs.io/en/latest/tutorials/tensorflow-serving-cluster/index.html), including two packages:
> - Kebubernetes. This directory contains Yaml configuration files of the serices
>   `flannel` and `ingress-nginx` and installation scrpts. We need to setup these
> ```

`scrpts` -> `scripts`. Please check this whole file with a spell checker, there are many obvious typos here.
___
*[tensorflow-serving-cluster/README.md, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0as7F9u190O9D3gGN:-MV0as7F9u190O9D3gGO:b63xjeq) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L11)):*
> ```Markdown
>   related scripts, the Yaml configuration of TensorFlow Serving in Kubernetes.
> 
> We build Kubernetes and TensorFlow Serving on Ubuntu18.04, with SGX platforms.
> ```

Better wording: `on SGX-enabled platforms with Ubuntu 18.04.`
___
*[tensorflow-serving-cluster/README.md, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0b0gZ1-51uZ8TaKFs:-MV0b0gZ1-51uZ8TaKFt:b-3t5bpc) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L17)):*
> ```Markdown
> Simply running a TensorFlow Serving system inside Graphene is not enough for a
> safe & secure end-user experience. Thus, there is a need to build a complete
> secure inferencing flow. This tutorial will present TensorFlow Serving with Intel
> ```

`This tutorial` -> `The linked tutorial`
___
*[tensorflow-serving-cluster/README.md, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0bCTD-YemcV7kDVdU:-MV0bCTD-YemcV7kDVdV:b-3t5bpc) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L26)):*
> ```Markdown
> The following steps should suffice to run the PPML on a Ubuntu 18.04 installation.
> 
> - Ubuntu 18.04. This tutorial should work on other Linux distributions as well,
> ```

`This tutorial` -> `The linked tutorial`
___
*[tensorflow-serving-cluster/README.md, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0bDVo62-DpqiQlGzh:-MV0bDVo62-DpqiQlGzi:b-2jn7w) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L34)):*
> ```Markdown
> 
> - Docker Engine. Docker Engine is an open source containerization technology for
>   building and containerizing your applications. In this tutorial, applications,
> ```

`In this tutorial` -> `In the linked tutorial`
___
*[tensorflow-serving-cluster/README.md, line 53 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0bMCh6r2oisnrcO4R:-MV0bMCh6r2oisnrcO4S:be9xqy4) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L53)):*
> ```Markdown
>   scaling, and management of containerized applications. In this tutorial, we
>   will provide a script (``install_kubernetes.sh``) to install Kubernetes in your
>   machine.
> ```

This sentence doesn't make sense -- you already provide the mentioned script in here. So please update this sentence accordingly (`We provide a script ... under directory ...`)
___
*[tensorflow-serving-cluster/README.md, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0bZhLCNJ5hcA0C9Rc:-MV0bZhLCNJ5hcA0C9Rd:b-2jn7w) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L60)):*
> ```Markdown
> 
> - Graphene. Follow [Quick Start](https://graphene.readthedocs.io/en/latest/quickstart.html)
>   to build Graphene. In this tutorial, we will need to build Graphene in the
> ```

`In this tutorial` -> `In the linked tutorial`
___
*[tensorflow-serving-cluster/README.md, line 63 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0ba0A4gvh3aaErDEH:-MV0ba0A4gvh3aaErDEI:bhqkoa) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L63)):*
> ```Markdown
>   host to get the tool ``pf_crypt``, which will be used to encrypt the model file.
> 
> - TensorFlow Serving cluster scripts package.
> ```

What is this? Isn't it your subdirectory `tensorflow-serving`? Then it's not a prerequisite, because it is provided here. Simply remove this sentence.
___
*[tensorflow-serving-cluster/README.md, line 68 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0bmtq2B9ucru5yupw:-MV0bmtrC2Jsg8EFVnmt:b-t5beow) ([raw file](https://github.com/oscarlab/graphene-cont [...]

2021-03-08 11:02 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 10 unresolved discussions (waiting on @mkow and @RodgerZhu)

___
*[tensorflow-serving-cluster/README.md, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0aO7P-2aAsHI0mjuN:-MVGTgd7AU3dwtJZwzyf:ble8auw) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `Kebubernetes` -> `Kubernetes`
</blockquote></details>

This is not yet fixed.
___
*[tensorflow-serving-cluster/README.md, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0bCTD-YemcV7kDVdU:-MVGTsh7BLDesrGpuN5G:but9550) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`This tutorial` -> `The linked tutorial`
</blockquote></details>

Not yet fixed.
___
*[tensorflow-serving-cluster/README.md, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0bDVo62-DpqiQlGzh:-MVGTuRa7le3SS5WawIx:but9550) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`In this tutorial` -> `In the linked tutorial`
</blockquote></details>

Not yet fixed.
___
*[tensorflow-serving-cluster/README.md, line 68 at r2](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MV0bmtq2B9ucru5yupw:-MVGU_1c416zJODHX8h_:ble8auw) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/cc9b3dc4bac028ec9838a7133c8c6b246248854f/tensorflow-serving-cluster/README.md#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to execute the provided scripts step by step`.
</blockquote></details>

This is not yet fixed.
___
*[tensorflow-serving-cluster/README.md, line 33 at r3](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MVGUEDa8uvbNKIdCPaQ:-MVGUEDa8uvbNKIdCPaR:bd07tiy) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/6e94707a1b039552d356efbc8e348f7a552fac49/tensorflow-serving-cluster/README.md#L33)):*
> ```Markdown
>   Please install additional DNS-resolver libraries::
> 
>      sudo apt install libnss-mdns libnss-myhostname
> ```

This is a Markdown file, so you should use the Markdown formatting (**not** the reST formatting). Please fix this.
___
*[tensorflow-serving-cluster/README.md, line 53 at r3](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MVGTxmf5CtLK7NjyHOZ:-MVGTxmf5CtLK7NjyHO_:b-2jn7w) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/6e94707a1b039552d356efbc8e348f7a552fac49/tensorflow-serving-cluster/README.md#L53)):*
> ```Markdown
> - Kubernetes. [Kubernetes](https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/)
>   is an open-source system for automating deployment,
>   scaling, and management of containerized applications. In this tutorial, we
> ```

`In this tutorial` -> `In the linked tutorial`
___
*[tensorflow-serving-cluster/README.md, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MVGUO785JWCxTPoNf1Z:-MVGUO785JWCxTPoNf1_:b-3h0er8) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/6e94707a1b039552d356efbc8e348f7a552fac49/tensorflow-serving-cluster/README.md#L54)):*
> ```Markdown
>   is an open-source system for automating deployment,
>   scaling, and management of containerized applications. In this tutorial, we
>   provide a script (``install_kubernetes.sh``) under `<graphene-contrib repository>/tensorflow-serving-cluster/kubernetes/`
> ```

This is a Markdown file. Please do not use double-backticks (they are used in reST but not in Markdown).
___
*[tensorflow-serving-cluster/README.md, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MVGUXDS-OY646Qrkx4B:-MVGUXDS-OY646Qrkx4C:b-3h0er8) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/6e94707a1b039552d356efbc8e348f7a552fac49/tensorflow-serving-cluster/README.md#L63)):*
> ```Markdown
> - Graphene. Follow [Quick Start](https://graphene.readthedocs.io/en/latest/quickstart.html)
>   to build Graphene. [In the linked tutorial](https://graphene.readthedocs.io/en/latest/tutorials/tensorflow-serving-cluster/index.html),
>   we will need to build Graphene in the host to get the tool ``pf_crypt``, which
> ```

This is a Markdown file. Please do not use double-backticks (they are used in reST but not in Markdown).
___
*[tensorflow-serving-cluster/tensorflow-serving/README.md, line 20 at r3](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MVGV1zm1fA7-POtFpsS:-MVGV1zm1fA7-POtFpsT:b-a5sg) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/6e94707a1b039552d356efbc8e348f7a552fac49/tensorflow-serving-cluster/tensorflow-serving/README.md#L20)):*
> ```Markdown
>   - `model_graph_to_saved_model.py` to convert the model file.
>   - `run_graphene_tf_serving.sh` and `run_tf_serving.sh` to run TensorFlow Serving
>   with Graphene and with natively (without Graphene).
> ```

`...and with natively...` -> `...and natively...`


<!-- Sent from Reviewable.io -->

2021-03-09 12:26 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

___
*[tensorflow-serving-cluster/README.md, line 49 at r4](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MVLvzmF2LSfLtkdAuxS:-MVLvzmG6853ChzSPN4S:b-d3q9gj) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/ce980edcd86a2ca251ef762362aed8f6ef3a45cd/tensorflow-serving-cluster/README.md#L49)):*
> ```Markdown
>   designed for production environments. Install::
> 
>      pip3 install -r <graphene-contrib repository>/tensorflow-serving-cluster/tensorflow-serving/client/requirements.txt
> ```

Here is one more reST-formatted piece. Please change to Markdown.


<!-- Sent from Reviewable.io -->

2021-03-10 08:07 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)



<!-- Sent from Reviewable.io -->

2021-03-16 00:43 UTC, RodgerZhu commented
@mkow, could you please help to have a review? Thanks :)

2021-03-22 14:56 UTC, mkow requested changes
> Reviewed 7 of 26 files at r1, 14 of 22 files at r2, 3 of 5 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPEp-K39MaZj87zsi3:-MWPEp-K39MaZj87zsi4:b-mrq5j1) (no related file):*
Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can push-force if you choose the former.

---
___
*[tensorflow-serving-cluster/README.md, line 21 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPQK5OAm3FAK_vsoc6:-MWPQK5OAm3FAK_vsoc7:b-n1jpm2) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/README.md#L21)):*
> ```Markdown
> will present TensorFlow Serving with Intel SGX and Graphene and will provide
> end-to-end protection (from client to servers) and integrate various security
> ingredients such as the load balancer (Nginx Ingress) and elastic scheduler
> ```

`Nginx` -> `nginx`
___
*[tensorflow-serving-cluster/README.md, line 54 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPFJkF0s5s6rAxpZGy:-MWPFJkF0s5s6rAxpZGz:bsaux1s) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/README.md#L54)):*
> ```Markdown
>   is an open-source system for automating deployment,
>   scaling, and management of containerized applications. In the linked tutorial,
>   we provide a script (`install_kubernetes.sh`) under `<graphene-contrib repository>/tensorflow-serving-cluster/kubernetes/` to install Kubernetes in your machine.
> ```

`in your machine` -> `on your machine`
___
*[tensorflow-serving-cluster/kubernetes/install_kubernetes.sh, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPFV8wDS1wo7CtfMfy:-MWPFV8wDS1wo7CtfMfz:b-depp5k) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/kubernetes/install_kubernetes.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

`#!/bin/bash` -> `#!/usr/bin/env bash`
___
*[tensorflow-serving-cluster/kubernetes/install_kubernetes.sh, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPFg1J8U-4UssiZC7H:-MWPFg1J8U-4UssiZC7I:b-6us2sl) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/kubernetes/install_kubernetes.sh#L3)):*
> ```Shell
> #!/bin/bash
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (C) 2021  Intel Corporation
> ```

We use a single space after the year in all other places.
___
*[tensorflow-serving-cluster/tensorflow-serving/download_model.sh, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIB_j6A8P3R0K7h6_:-MWPIB_j6A8P3R0K7h6a:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/download_model.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

ditto
___
*[tensorflow-serving-cluster/tensorflow-serving/download_model.sh, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIC7a7bGrd0fMGsXd:-MWPIC7a7bGrd0fMGsXe:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/download_model.sh#L3)):*
> ```Shell
> #!/bin/bash
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (C) 2021  Intel Corporation
> ```

ditto
___
*[tensorflow-serving-cluster/tensorflow-serving/download_model.sh, line 15 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIHYL-41dfxNBYcqu:-MWPIHYL-41dfxNBYcqv:b47zakp) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/download_model.sh#L15)):*
> ```
> --no-check-certificate
> ```

Why using this option?
___
*[tensorflow-serving-cluster/tensorflow-serving/generate_ssl_config.sh, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPINTfChJr_GQBsGx6:-MWPINTfChJr_GQBsGx7:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/generate_ssl_config.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

ditto
___
*[tensorflow-serving-cluster/tensorflow-serving/generate_ssl_config.sh, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIO0w77QjcNre-4ZO:-MWPIO0w77QjcNre-4ZP:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/generate_ssl_config.sh#L3)):*
> ```Shell
> #!/bin/bash
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (C) 2021  Intel Corporation
> ```

ditto
___
*[tensorflow-serving-cluster/tensorflow-serving/model_graph_to_saved_model.py, line 2 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIW20DOrs0LsihB31:-MWPIW20DOrs0LsihB32:bd11qa0) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/model_graph_to_saved_model.py#L2)):*
> ```Python
> #
> # -*- coding: utf-8 -*-
> ```

not needed, this is default in Python3 AFAIK
___
*[tensorflow-serving-cluster/tensorflow-serving/model_graph_to_saved_model.py, line 4 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPI_nV7DAfbBMwHtEl:-MWPI_nV7DAfbBMwHtEm:b-8k88ng) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/model_graph_to_saved_model.py#L4)):*
> ```Python
> # -*- coding: utf-8 -*-
> #
> # Copyright (c) 2019 Intel Corporation
> ```

2019?
___
*[tensorflow-serving-cluster/tensorflow-serving/model_graph_to_saved_model.py, line 18 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIeW--y8CnZcxTBBp:-MWPIeW--y8CnZcxTBBq:b-199kfc) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/model_graph_to_saved_model.py#L18)):*
> ```Python
> # limitations under the License.
> #
> # SPDX-License-Identifier: EPL-2.0
> ```

`EPL-2.0`? I guess this file was copy-pasted from somewhere? Can we actually legally include it in our sources?
___
*[tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPJWCO9IPW4RIIRM-O:-MWPJWCO9IPW4RIIRM-P:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

ditto
___
*[tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPJWpz2l7d2NHOrx6h:-MWPJWpz2l7d2NHOrx6i:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh#L3)):*
> ```Shell
> #!/bin/bash
> # SPDX-License-Identifier: LGPL-3.0-or-later
> # Copyright (C) 2021  Intel Corporation
> ```

ditto
___
*[tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh, line 18 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPJoIHB6YYxt0WSAMi:-MWPJoIHB6YYxt0WSAMj:b-i4teeg) ([raw file](https:/ [...]

2021-03-30 19:03 UTC, mkow requested changes
@rodgerzhu Please use reviewable for reviews, it's quite hard to review your changes without your replies.

> Reviewed 3 of 22 files at r2, 15 of 15 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-:-MX3VujM2z_ie5u8PRYi:bf7sqj2)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @RodgerZhu)

___
*[tensorflow-serving-cluster/kubernetes/install_kubernetes.sh, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPFg1J8U-4UssiZC7H:-MX3SfsK7aoYoipbL-vT:b4kgaaq) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/kubernetes/install_kubernetes.sh#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We use a single space after the year in all other places.
</blockquote></details>

Now your name is misaligned.
___
*[tensorflow-serving-cluster/tensorflow-serving/download_model.sh, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIC7a7bGrd0fMGsXd:-MX3T-O35ettsrCs9rKy:b-kuty1j) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/download_model.sh#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto (same in all other places in this PR)
___
*[tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh, line 10 at r6](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MX3U-rJ4hYTdiB4fAwb:-MX3U-rKAgzBDGDoEs4W:bomcw20) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/501cb4bac482a2a46e4eb3395f6fb7ae48b8b65b/tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh#L10)):*
> ```Shell
> function usage_help() {
>     echo -e "options:"
>     echo -e "  -d Display help"
> ```

Please use `-h` for help, this is a standard almost everywhere (also, you didn't update the code below correctly, there's no handling for `-d`.
___
*[tensorflow-serving-cluster/tensorflow-serving/run_tf_serving.sh, line 12 at r6](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MX3U__P38WvzR4Ebrly:-MX3U__P38WvzR4Ebrlz:bsbktna) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/501cb4bac482a2a46e4eb3395f6fb7ae48b8b65b/tensorflow-serving-cluster/tensorflow-serving/run_tf_serving.sh#L12)):*
> ```Shell
>     echo -e "  -h Display help"
>     echo -e "  -i {image_id}"
>     echo -e "  -h {host_ports}"
> ```

duplicated switch
___
*[tensorflow-serving-cluster/tensorflow-serving/client/resnet_client_grpc.py, line 39 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPLeuZ6yCFWXEyX2kx:-MX3UjtPDe6QJ__JWNu7:bsdr2kg) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/client/resnet_client_grpc.py#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> print('not support batch n!=1 with image!')
> ```
please fix grammar here
</blockquote></details>

not done
possible fix: "Batch size >= 1 is not supported"
___
*[tensorflow-serving-cluster/tensorflow-serving/client/utils.py, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPMOSK6E7vv354YvXA:-MX3V2zp40bHytjnkkLr:bz4dnsn) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/client/utils.py#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Intel Corp.` -> `Intel Corporation`
</blockquote></details>

And no period at the end (please just mirror exactly the same formatting as we use in our repo)
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile, line 33 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPMj5v7bkrj9aTaf2y:-MX3VIZB60eC5FrVYDFJ:b-hndcz9) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

not done?
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/sgx_default_qcnl.conf, line 4 at r6](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MX3VinBEWVvY_YxOl3c:-MX3VinBEWVvY_YxOl3d:b-gcgodc) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/501cb4bac482a2a46e4eb3395f6fb7ae48b8b65b/tensorflow-serving-cluster/tensorflow-serving/docker/sgx_default_qcnl.conf#L4)):*
> ```
> #PCCS_URL=https://localhost:8081/sgx/certification/v3/
> #Need to change default local PCCS url to remote PCCS
> #Connect to PCCS on the remote machine
> ```

Missing space after `#`


<!-- Sent from Reviewable.io -->

2021-03-31 07:53 UTC, RodgerZhu commented
Hi @mkow , as I can't open reviewable to reply your comments directly, so please help to see the update commits.

2021-03-31 09:23 UTC, BuJianlin commented on tensorflow-serving-cluster/kubernetes/flannel/README.md
> +Falnnel is a simple and easy way to configure a layer 3 network fabric designed
It is "Flannel" instead of "Falnnel" .

2021-03-31 09:28 UTC, BuJianlin commented on tensorflow-serving-cluster/tensorflow-serving/docker/build_graphene_tf_serving_image.sh
> +    --build-arg no_proxy=localhost,127.0.0.0/1 \
use "    --build-arg no_proxy=localhost,127.0.0.0/1" instead of "    --build-arg no_proxy=localhost,127.0.0.0/1 \"

2021-04-02 11:05 UTC, BuJianlin commented
https://github.com/oscarlab/graphene-contrib/blob/033f3140bea60f0c423ab42e2594f4f659c528da/tensorflow-serving-cluster/tensorflow-serving/run_tf_serving.sh#L7

https://github.com/oscarlab/graphene-contrib/blob/033f3140bea60f0c423ab42e2594f4f659c528da/tensorflow-serving-cluster/tensorflow-serving/run_tf_serving.sh#L32

https://github.com/oscarlab/graphene-contrib/blob/033f3140bea60f0c423ab42e2594f4f659c528da/tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh#L7

https://github.com/oscarlab/graphene-contrib/blob/033f3140bea60f0c423ab42e2594f4f659c528da/tensorflow-serving-cluster/tensorflow-serving/run_graphene_tf_serving.sh#L38

@RodgerZhu 
Parameters mapped `function` and `getopts`are not aligned and repeated, please fix it.

2021-04-06 13:26 UTC, dimakuv reviewed
> Reviewed 4 of 15 files at r6, 8 of 11 files at r7, 2 of 2 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

___
*[tensorflow-serving-cluster/tensorflow-serving/client/utils.py, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPMOSK6E7vv354YvXA:-MXbL3x1CjphkeEcKSVB:b-3tfdwb) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/client/utils.py#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

And no period at the end (please just mirror exactly the same formatting as we use in our repo)
</blockquote></details>

@mkow But why? This will look ugly, and we don't have such formatting: https://github.com/oscarlab/graphene/search?p=2&q=intel+corporation.

For uniformity with the rest of the Graphene repo, we should do this:
```
# Copyright (C) 2021 Intel Corporation
#                    Yunge Zhu <yunge.zhu@intel.linux.com>
```
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile, line 33 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPMj5v7bkrj9aTaf2y:-MXbKBvh6oFUP9sCP19q:b-qbb10x) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not done?
</blockquote></details>

The sorting is weird. It should be alphabetic sort, not the current one. Like this:
```
RUN apt-get update \
    && apt-get install -y \
        autoconf \
        bison \
        build-essential \
        coreutils \
        ...
```
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/sgx_default_qcnl.conf, line 4 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPOj8s0gc6waQHjm03:-MXbKj7N5Nz01cjnudln:b-mghqq) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/docker/sgx_default_qcnl.conf#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why would we do this?
</blockquote></details>

I guess this setting is because the PCCS server is installed locally without proper PKI (it is self-signed or something).

For the tutorial, I think it's fine. I would put an additional comment here: `# NOTE: This is insecure and only for the purposes of the tutorial!`


<!-- Sent from Reviewable.io -->

2021-04-12 07:43 UTC, dimakuv reviewed
> Reviewed 11 of 11 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)



<!-- Sent from Reviewable.io -->

2021-05-08 01:08 UTC, mkow requested changes
> Reviewed 1 of 11 files at r7, 1 of 2 files at r8, 11 of 11 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @RodgerZhu)

___
*[tensorflow-serving-cluster/tensorflow-serving/download_model.sh, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIC7a7bGrd0fMGsXd:-M_8TvLQ3_NsoA0_Dja4:b-g2w16c) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/download_model.sh#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (same in all other places in this PR)
</blockquote></details>

Not fixed.
___
*[tensorflow-serving-cluster/tensorflow-serving/client/utils.py, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPMOSK6E7vv354YvXA:-M_8T1_x0O4OBlFgIALy:b5m9krw) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/client/utils.py#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow But why? This will look ugly, and we don't have such formatting: https://github.com/oscarlab/graphene/search?p=2&q=intel+corporation.

For uniformity with the rest of the Graphene repo, we should do this:
```
# Copyright (C) 2021 Intel Corporation
#                    Yunge Zhu <yunge.zhu@intel.linux.com>
```
</blockquote></details>

Hmm? Isn't this exactly what I suggested?
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile, line 33 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPMj5v7bkrj9aTaf2y:-M_8V7jzDR2RebiRIoCW:bmqj22t) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The sorting is weird. It should be alphabetic sort, not the current one. Like this:
```
RUN apt-get update \
    && apt-get install -y \
        autoconf \
        bison \
        build-essential \
        coreutils \
        ...
```
</blockquote></details>

Still not sorted. Please just use a sorting function from your code editor, I think all existing ones have such a functionality.
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/sgx_default_qcnl.conf, line 4 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPOj8s0gc6waQHjm03:-M_8Vx8AETVbctRpVAO9:bfjdifj) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/docker/sgx_default_qcnl.conf#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess this setting is because the PCCS server is installed locally without proper PKI (it is self-signed or something).

For the tutorial, I think it's fine. I would put an additional comment here: `# NOTE: This is insecure and only for the purposes of the tutorial!`
</blockquote></details>

Hmm, but now the comment is on a wrong line. It's `USE_SECURE_CERT=FALSE` which is insecure.


<!-- Sent from Reviewable.io -->

2021-05-10 09:54 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

___
*[tensorflow-serving-cluster/tensorflow-serving/download_model.sh, line 3 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPIC7a7bGrd0fMGsXd:-M_KgZhf2-JQB5RQLZ6M:b-klq4ss) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/download_model.sh#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not fixed.
</blockquote></details>

There is still a dot which is not needed: `Intel Corporation.`. Please remove the dot.
___
*[tensorflow-serving-cluster/tensorflow-serving/client/resnet_client_grpc.py, line 29 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPLPBW1k_rLsIhPn7C:-M_KgSqqA_c_daenYeNQ:b-z2z03b) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/client/resnet_client_grpc.py#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

This `pass` is not yet removed, @rodgerzhu . Please remove this line.
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile, line 33 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPMj5v7bkrj9aTaf2y:-M_KgKNr7Iq86tYcSAsm:b-gi74ma) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/docker/graphene_tf_serving.dockerfile#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Still not sorted. Please just use a sorting function from your code editor, I think all existing ones have such a functionality.
</blockquote></details>

LGTM. Looks like it was fixed now.
___
*[tensorflow-serving-cluster/tensorflow-serving/docker/sgx_default_qcnl.conf, line 4 at r5](https://reviewable.io/reviews/oscarlab/graphene-contrib/1#-MWPOj8s0gc6waQHjm03:-M_Kg5LqAqcZC6CKDmjm:b-gi74ma) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/a93f5b548bde3f92d33346dbb6ad70a9080f59d4/tensorflow-serving-cluster/tensorflow-serving/docker/sgx_default_qcnl.conf#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but now the comment is on a wrong line. It's `USE_SECURE_CERT=FALSE` which is insecure.
</blockquote></details>

LGTM. Looks like it was fixed now.


<!-- Sent from Reviewable.io -->

2021-05-10 11:00 UTC, mkow reviewed
> Reviewed 2 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @RodgerZhu)



<!-- Sent from Reviewable.io -->

2021-05-11 06:32 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/1)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @RodgerZhu)



<!-- Sent from Reviewable.io -->

2021-06-16 09:14 UTC, closed without merging

2021-06-16 09:15 UTC, RodgerZhu commented
move this PR to https://github.com/oscarlab/graphene-contrib/pull/4